name: Build docker image
on: 
  push:
    branches:
    - '*'

jobs:
  base-image:
    runs-on: ubuntu-18.04
    steps:
      - name: Get file changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','
      - name: changed_yml
        id: changed_yml
        run: |
          if grep renv.lock $HOME/files_modified.csv; then
            MODIFIED=$(grep renv.lock $HOME/files_modified.csv)
          else
            MODIFIED="nope"
          fi
          
          echo ::set-output name=RENV_MODIFIED::$MODIFIED
      - name: Testyml
        run: echo ${{steps.changed_yml.outputs.RENV_MODIFIED}}
      - name: TestId
        if: contains(steps.changed_yml.outputs.RENV_MODIFIED, 'renv.lock')
        run: echo "yeysyeysyeys"
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
# #     - name: Run Docker build
# #       id: get_version
# #       run: docker build -f test-docker/Dockerfile ./test-docker
#     - name: Test echo
#       id: test_echo
#       run: echo "Hello"
#     - name: Test echo of secret into file
#       run: |
#         echo "texts"
#       env:
#         FINGERPRINT: ${{secrets.RANDOM_KEY}} 
#     - name: demo
#       id: demo_it
#       run: REPO=$( echo "${{ github.repository }}" | echo $(awk '{print tolower($0)}') )
#     - name: Test bash to lower
#       id: test_bash
#       run: echo "${REPO,,}"; 
