name: Build docker image
on: 
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
#     - name: Run Docker build
#       id: get_version
#       run: docker build -f test-docker/Dockerfile ./test-docker
    - name: Test echo
      id: test_echo
      run: echo "Hello"
    - name: Test bash to lower
      id: test_bash
      run: echo "${${{ github.repository }},,}"; 
